-- Supabase/PostgreSQL schema for the portfolio backend.
-- Run this once in the Supabase SQL editor.

create extension if not exists pgcrypto;

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique,
  summary text not null,
  description text not null default '',
  tech_stack text[] not null default '{}',
  repository_url text,
  demo_url text,
  image_url text,
  featured boolean not null default false,
  display_order integer not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists projects_published_order_idx
  on public.projects (published, display_order, created_at desc);

create table if not exists public.certificates (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  issuer text not null default '',
  issued_on date,
  credential_url text,
  image_url text,
  description text not null default '',
  display_order integer not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists certificates_published_order_idx
  on public.certificates (published, display_order, created_at desc);

create table if not exists public.contact_messages (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  subject text not null default '',
  message text not null,
  page_url text,
  status text not null default 'new'
    check (status in ('new', 'read', 'archived')),
  email_status text not null default 'pending'
    check (email_status in ('pending', 'sent', 'failed', 'skipped')),
  email_error text,
  created_at timestamptz not null default now(),
  read_at timestamptz,
  archived_at timestamptz
);

create index if not exists contact_messages_status_idx
  on public.contact_messages (status, created_at desc);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null
    check (event_name in (
      'visit',
      'section_view',
      'project_click',
      'repo_click',
      'demo_click',
      'contact_start',
      'contact_submit',
      'game_start',
      'game_complete'
    )),
  event_date date not null default current_date,
  section text,
  project_slug text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_date_name_idx
  on public.analytics_events (event_date, event_name);

create index if not exists analytics_events_section_idx
  on public.analytics_events (event_date, section);

-- Service-role API access is used by Netlify Functions.
-- Keep RLS enabled so accidental anonymous access remains blocked.
alter table public.projects enable row level security;
alter table public.certificates enable row level security;
alter table public.contact_messages enable row level security;
alter table public.analytics_events enable row level security;

-- No public policies are created intentionally.
-- The server-side Supabase service-role key bypasses RLS and never reaches the browser.
